Write a Python script that takes in a letter and sends a POST request to http://0.0.0.0:5000/search_user with the letter as a parameter.

The letter must be sent in the variable q
If no argument is given, set q=""
If the response body is properly JSON formatted and not empty, display the id and name like this: [<id>] <name>
Otherwise:
Display Not a valid JSON if the JSON is invalid
Display No result if the JSON is empty
You must use the package requests and sys
You are not allowed to import packages other than requests and sys
Please test your script in the container provided, using the web server running on port 5000. All JSON generated by this server are random.

guillaume@ubuntu:~/$ ./5-json_api.py
No result
guillaume@ubuntu:~/$ ./5-json_api.py a
[8446] amnirqhtfjq
guillaume@ubuntu:~/$ ./5-json_api.py 2
No result
guillaume@ubuntu:~/$ ./5-json_api.py b
[7094] bmofakakhke
guillaume@ubuntu:~/$